## importando librerias
from tkinter import *
from tkinter import messagebox
from time import sleep
from tkinter import ttk
import pygame
import subprocess
import pymysql

##Creacion de la ventanas
raiz = Tk ()
raiz.resizable ( 0, 0 )
raiz.title ( "GATO GRAFICO" )
raiz.geometry ( "700x450" )
raiz.config ( bg = "steel blue" )
raiz.config ( cursor = "plus" )

def abre():
    subprocess.Popen(["Python","prueba.py"])
##Imagenes de el gato
etiqueta=PhotoImage(file="fondo win.png")
bloque2=PhotoImage( file= 'bloque2.gif' )
Retro_Mario2=PhotoImage( file= 'Retro_Mario2.png' )
bowser=PhotoImage(file="bowserclassic2.png")
fondo=PhotoImage(file="fondo win.png")
f=PhotoImage(file="pantalla.png")
pantalla=Label(raiz,image=f)
pantalla.place(x=1,y=1)

##Creando variables de caracteres
reset=StringVar()
g1=StringVar()
g2=StringVar()
g3=StringVar()
g4=StringVar()
g5=StringVar()
g6=StringVar()
g7=StringVar()
g8=StringVar()
g9=StringVar()
g1.set("1")
g2.set("2")
g3.set("3")
g4.set("4")
g5.set("5")
g6.set("6")
g7.set("7")
g8.set("8")
g9.set("9")
jugador=StringVar()
m=StringVar()
jugador.set("MARIO")
##Creacion de Cancion de fondo
pygame.init()
pygame.mixer.music.load("sonido1.mp3")
pygame.mixer.music.play(2)
## contador de mario
contador=StringVar()
contador.set("0")
suma=StringVar()
suma.set("1")
## contador de bowser
contador2=StringVar()
contador2.set("0")
suma2=StringVar()
suma2.set("1")
##Empate
empate=StringVar()
empate.set("9")
fin=StringVar()
fin.set("1")
##Conexion con la base de datos
def Base():
     conn=pymysql.connect(host='localhost',port=33063, user='root', passwd='', db='test2')
     cursor=conn.cursor()
     cursor.execute("select nom_usuario from usuarios")
     listado = []
     for row in cursor:
         listado.append(row)
         conn.commit ()
     despliega1["values"] = listado
     despliega2["values"] = listado
     cursor.close()
     conn.close()
##Actualiza el combobox
def update():
    conn = pymysql.connect (host='localhost', port=33063, user='root', passwd='', db='test2')
    cursor = conn.cursor ()
    cursor.execute ("select nom_usuario from usuarios")
    listado = []
    for row in cursor:
        listado.append (row)
    despliega1["values"] = listado
    despliega2["values"] = listado
    cursor.close ()
    conn.close ()

##Aqui se crean los combo box
despliega1=ttk.Combobox(raiz)
despliega1.place(x=355,y=100)
despliega2=ttk.Combobox(raiz)
despliega2.place(x=355,y=150)

##gif de mario
def celebra_mario():
    pygame.init ()
    pygame.mixer.music.load ("sonido2.mp3")
    vec=[(PhotoImage(file="./mario 64/0.gif"))]
    vec.append(PhotoImage(file="./mario 64/1.gif"))
    vec.append(PhotoImage(file="./mario 64/2.gif"))
    vec.append(PhotoImage(file="./mario 64/3.gif"))
    vec.append(PhotoImage(file="./mario 64/4.gif"))
    vec.append(PhotoImage(file="./mario 64/5.gif"))
    vec.append(PhotoImage(file="./mario 64/6.gif"))
    vec.append(PhotoImage(file="./mario 64/7.gif"))
    vec.append(PhotoImage(file="./mario 64/8.gif"))
    vec.append(PhotoImage(file="./mario 64/9.gif"))
    vec.append (PhotoImage (file="./mario 64/10.gif"))
    vec.append (PhotoImage (file="./mario 64/11.gif"))
    vec.append (PhotoImage (file="./mario 64/12.gif"))
    vec.append (PhotoImage (file="./mario 64/13.gif"))
    vec.append (PhotoImage (file="./mario 64/14.gif"))
    vec.append (PhotoImage (file="./mario 64/15.gif"))
    vec.append (PhotoImage (file="./mario 64/16.gif"))
    vec.append (PhotoImage (file="./mario 64/17.gif"))
    vec.append (PhotoImage (file="./mario 64/18.gif"))
    vec.append (PhotoImage (file="./mario 64/19.gif"))
    vec.append (PhotoImage (file="./mario 64/20.gif"))
    vec.append (PhotoImage (file="./mario 64/21.gif"))
    vec.append (PhotoImage (file="./mario 64/22.gif"))
    vec.append (PhotoImage (file="./mario 64/23.gif"))
    vec.append (PhotoImage (file="./mario 64/24.gif"))
    vec.append (PhotoImage (file="./mario 64/25.gif"))
    vec.append (PhotoImage (file="./mario 64/26.gif"))
    vec.append (PhotoImage (file="./mario 64/27.gif"))
    vec.append (PhotoImage (file="./mario 64/28.gif"))
    vec.append (PhotoImage (file="./mario 64/29.gif"))
    vec.append (PhotoImage (file="./mario 64/30.gif"))
    vec.append (PhotoImage (file="./mario 64/31.gif"))
    vec.append (PhotoImage (file="./mario 64/32.gif"))
    vec.append (PhotoImage (file="./mario 64/33.gif"))
    vec.append (PhotoImage (file="./mario 64/34.gif"))
    vec.append (PhotoImage (file="./mario 64/35.gif"))
    vec.append (PhotoImage (file="./mario 64/36.gif"))
    vec.append (PhotoImage (file="./mario 64/37.gif"))
    vec.append (PhotoImage (file="./mario 64/38.gif"))
    vec.append (PhotoImage (file="./mario 64/39.gif"))
    vec.append (PhotoImage (file="./mario 64/40.gif"))
    vec.append (PhotoImage (file="./mario 64/41.gif"))
    vec.append (PhotoImage (file="./mario 64/42.gif"))
    vec.append (PhotoImage (file="./mario 64/43.gif"))
    vec.append (PhotoImage (file="./mario 64/44.gif"))
    vec.append (PhotoImage (file="./mario 64/45.gif"))
    vec.append (PhotoImage (file="./mario 64/46.gif"))
    vec.append (PhotoImage (file="./mario 64/47.gif"))
    vec.append (PhotoImage (file="./mario 64/48.gif"))
    vec.append (PhotoImage (file="./mario 64/49.gif"))
    vec.append (PhotoImage (file="./mario 64/50.gif"))
    vec.append (PhotoImage (file="./mario 64/51.gif"))
    vec.append (PhotoImage (file="./mario 64/52.gif"))
    vec.append (PhotoImage (file="./mario 64/53.gif"))
    vec.append (PhotoImage (file="./mario 64/54.gif"))
    vec.append (PhotoImage (file="./mario 64/55.gif"))
    vec.append (PhotoImage (file="./mario 64/56.gif"))
    vec.append (PhotoImage (file="./mario 64/57.gif"))
    vec.append (PhotoImage (file="./mario 64/58.gif"))
    vec.append (PhotoImage (file="./mario 64/59.gif"))
    vec.append (PhotoImage (file="./mario 64/60.gif"))
    vec.append (PhotoImage (file="./mario 64/61.gif"))
    vec.append (PhotoImage (file="./mario 64/62.gif"))
    vec.append (PhotoImage (file="./mario 64/63.gif"))
    vec.append (PhotoImage (file="./mario 64/64.gif"))
    vec.append (PhotoImage (file="./mario 64/65.gif"))
    vec.append (PhotoImage (file="./mario 64/66.gif"))
    vec.append (PhotoImage (file="./mario 64/67.gif"))
    vec.append (PhotoImage (file="./mario 64/68.gif"))
    vec.append (PhotoImage (file="./mario 64/69.gif"))
    vec.append (PhotoImage (file="./mario 64/70.gif"))
    vec.append (PhotoImage (file="./mario 64/71.gif"))
    vec.append (PhotoImage (file="./mario 64/72.gif"))
    vec.append (PhotoImage (file="./mario 64/73.gif"))
    vec.append (PhotoImage (file="./mario 64/74.gif"))
    vec.append (PhotoImage (file="./mario 64/75.gif"))
    vec.append (PhotoImage (file="./mario 64/76.gif"))
    vec.append (PhotoImage (file="./mario 64/77.gif"))
    vec.append (PhotoImage (file="./mario 64/78.gif"))
    vec.append (PhotoImage (file="./mario 64/79.gif"))
    vec.append (PhotoImage (file="./mario 64/80.gif"))
    vec.append (PhotoImage (file="./mario 64/81.gif"))
    vec.append (PhotoImage (file="./mario 64/82.gif"))
    vec.append (PhotoImage (file="./mario 64/83.gif"))
    vec.append (PhotoImage (file="./mario 64/84.gif"))
    vec.append (PhotoImage (file="./mario 64/85.gif"))
    vec.append (PhotoImage (file="./mario 64/86.gif"))
    vec.append (PhotoImage (file="./mario 64/87.gif"))
    vec.append (PhotoImage (file="./mario 64/88.gif"))
    vec.append (PhotoImage (file="./mario 64/89.gif"))
    vec.append (PhotoImage (file="./mario 64/90.gif"))
    vec.append (PhotoImage (file="./mario 64/91.gif"))
    vec.append (PhotoImage (file="./mario 64/92.gif"))
    vec.append (PhotoImage (file="./mario 64/93.gif"))
    vec.append (PhotoImage (file="./mario 64/94.gif"))
    vec.append (PhotoImage (file="./mario 64/95.gif"))
    vec.append (PhotoImage (file="./mario 64/96.gif"))
    vec.append (PhotoImage (file="./mario 64/97.gif"))
    vec.append (PhotoImage (file="./mario 64/98.gif"))
    vec.append (PhotoImage (file="./mario 64/99.gif"))
    vec.append (PhotoImage (file="./mario 64/100.gif"))
    vec.append (PhotoImage (file="./mario 64/101.gif"))
    vec.append (PhotoImage (file="./mario 64/102.gif"))
    vec.append (PhotoImage (file="./mario 64/103.gif"))
    vec.append (PhotoImage (file="./mario 64/104.gif"))
    vec.append (PhotoImage (file="./mario 64/105.gif"))
    vec.append (PhotoImage (file="./mario 64/106.gif"))
    vec.append (PhotoImage (file="./mario 64/107.gif"))
    vec.append (PhotoImage (file="./mario 64/108.gif"))
    vec.append (PhotoImage (file="./mario 64/109.gif"))
    vec.append (PhotoImage (file="./mario 64/110.gif"))
    vec.append (PhotoImage (file="./mario 64/111.gif"))
    vec.append (PhotoImage (file="./mario 64/112.gif"))
    vec.append (PhotoImage (file="./mario 64/113.gif"))
    vec.append (PhotoImage (file="./mario 64/114.gif"))
    vec.append (PhotoImage (file="./mario 64/115.gif"))
    vec.append (PhotoImage (file="./mario 64/116.gif"))
    vec.append (PhotoImage (file="./mario 64/117.gif"))
    vec.append (PhotoImage (file="./mario 64/118.gif"))
    vec.append (PhotoImage (file="./mario 64/119.gif"))
    vec.append (PhotoImage (file="./mario 64/120.gif"))
    vec.append (PhotoImage (file="./mario 64/121.gif"))
    vec.append (PhotoImage (file="./mario 64/122.gif"))
    vec.append (PhotoImage (file="./mario 64/123.gif"))
    vec.append (PhotoImage (file="./mario 64/124.gif"))
    vec.append (PhotoImage (file="./mario 64/125.gif"))
    vec.append (PhotoImage (file="./mario 64/126.gif"))
    vec.append (PhotoImage (file="./mario 64/127.gif"))
    vec.append (PhotoImage (file="./mario 64/128.gif"))
    vec.append (PhotoImage (file="./mario 64/129.gif"))
    vec.append (PhotoImage (file="./mario 64/130.gif"))
    vec.append (PhotoImage (file="./mario 64/131.gif"))
    vec.append (PhotoImage (file="./mario 64/132.gif"))
    vec.append (PhotoImage (file="./mario 64/133.gif"))
    vec.append (PhotoImage (file="./mario 64/134.gif"))
    vec.append (PhotoImage (file="./mario 64/135.gif"))
    vec.append (PhotoImage (file="./mario 64/136.gif"))
    vec.append (PhotoImage (file="./mario 64/137.gif"))
    vec.append (PhotoImage (file="./mario 64/138.gif"))
    vec.append (PhotoImage (file="./mario 64/139.gif"))
    vec.append (PhotoImage (file="./mario 64/140.gif"))
    vec.append (PhotoImage (file="./mario 64/141.gif"))

    pygame.mixer.music.play (1)
    for i in range(0,141):
        win.config(image=vec[i])
        raiz.update()
        sleep(.02)
    win.config(image=fondo)
    raiz.update()

##gif bowser
def celebra_bowser():
    pygame.init ()
    pygame.mixer.music.load ("sonido3.mp3")
    vec = [(PhotoImage (file="./bowser 64/0.gif"))]
    vec.append (PhotoImage (file="./bowser 64/1.gif"))
    vec.append (PhotoImage (file="./bowser 64/2.gif"))
    vec.append (PhotoImage (file="./bowser 64/3.gif"))
    vec.append (PhotoImage (file="./bowser 64/4.gif"))
    vec.append (PhotoImage (file="./bowser 64/5.gif"))
    vec.append (PhotoImage (file="./bowser 64/6.gif"))
    vec.append (PhotoImage (file="./bowser 64/7.gif"))
    vec.append (PhotoImage (file="./bowser 64/8.gif"))
    vec.append (PhotoImage (file="./bowser 64/9.gif"))
    vec.append (PhotoImage (file="./bowser 64/10.gif"))
    vec.append (PhotoImage (file="./bowser 64/11.gif"))
    vec.append (PhotoImage (file="./bowser 64/12.gif"))
    vec.append (PhotoImage (file="./bowser 64/13.gif"))
    vec.append (PhotoImage (file="./bowser 64/14.gif"))
    vec.append (PhotoImage (file="./bowser 64/15.gif"))
    vec.append (PhotoImage (file="./bowser 64/16.gif"))
    vec.append (PhotoImage (file="./bowser 64/17.gif"))
    vec.append (PhotoImage (file="./bowser 64/18.gif"))
    vec.append (PhotoImage (file="./bowser 64/19.gif"))
    vec.append (PhotoImage (file="./bowser 64/20.gif"))
    vec.append (PhotoImage (file="./bowser 64/21.gif"))
    vec.append (PhotoImage (file="./bowser 64/22.gif"))
    vec.append (PhotoImage (file="./bowser 64/23.gif"))
    vec.append (PhotoImage (file="./bowser 64/24.gif"))
    vec.append (PhotoImage (file="./bowser 64/25.gif"))
    vec.append (PhotoImage (file="./bowser 64/26.gif"))
    vec.append (PhotoImage (file="./bowser 64/27.gif"))
    vec.append (PhotoImage (file="./bowser 64/28.gif"))
    vec.append (PhotoImage (file="./bowser 64/29.gif"))
    vec.append (PhotoImage (file="./bowser 64/30.gif"))
    vec.append (PhotoImage (file="./bowser 64/31.gif"))
    vec.append (PhotoImage (file="./bowser 64/32.gif"))
    vec.append (PhotoImage (file="./bowser 64/33.gif"))
    vec.append (PhotoImage (file="./bowser 64/34.gif"))
    vec.append (PhotoImage (file="./bowser 64/35.gif"))
    vec.append (PhotoImage (file="./bowser 64/36.gif"))
    vec.append (PhotoImage (file="./bowser 64/37.gif"))
    vec.append (PhotoImage (file="./bowser 64/38.gif"))
    vec.append (PhotoImage (file="./bowser 64/39.gif"))
    vec.append (PhotoImage (file="./bowser 64/40.gif"))
    vec.append (PhotoImage (file="./bowser 64/41.gif"))
    vec.append (PhotoImage (file="./bowser 64/42.gif"))
    vec.append (PhotoImage (file="./bowser 64/43.gif"))
    vec.append (PhotoImage (file="./bowser 64/44.gif"))
    vec.append (PhotoImage (file="./bowser 64/45.gif"))
    vec.append (PhotoImage (file="./bowser 64/46.gif"))
    vec.append (PhotoImage (file="./bowser 64/47.gif"))
    vec.append (PhotoImage (file="./bowser 64/48.gif"))
    vec.append (PhotoImage (file="./bowser 64/49.gif"))
    vec.append (PhotoImage (file="./bowser 64/50.gif"))
    vec.append (PhotoImage (file="./bowser 64/51.gif"))
    vec.append (PhotoImage (file="./bowser 64/52.gif"))
    vec.append (PhotoImage (file="./bowser 64/53.gif"))
    vec.append (PhotoImage (file="./bowser 64/54.gif"))
    vec.append (PhotoImage (file="./bowser 64/55.gif"))
    vec.append (PhotoImage (file="./bowser 64/56.gif"))
    vec.append (PhotoImage (file="./bowser 64/57.gif"))
    vec.append (PhotoImage (file="./bowser 64/58.gif"))
    vec.append (PhotoImage (file="./bowser 64/59.gif"))
    vec.append (PhotoImage (file="./bowser 64/60.gif"))
    vec.append (PhotoImage (file="./bowser 64/61.gif"))
    vec.append (PhotoImage (file="./bowser 64/62.gif"))
    vec.append (PhotoImage (file="./bowser 64/63.gif"))
    vec.append (PhotoImage (file="./bowser 64/64.gif"))
    vec.append (PhotoImage (file="./bowser 64/65.gif"))
    vec.append (PhotoImage (file="./bowser 64/66.gif"))
    vec.append (PhotoImage (file="./bowser 64/67.gif"))
    vec.append (PhotoImage (file="./bowser 64/68.gif"))
    vec.append (PhotoImage (file="./bowser 64/69.gif"))
    vec.append (PhotoImage (file="./bowser 64/70.gif"))
    vec.append (PhotoImage (file="./bowser 64/71.gif"))
    vec.append (PhotoImage (file="./bowser 64/72.gif"))
    vec.append (PhotoImage (file="./bowser 64/73.gif"))
    vec.append (PhotoImage (file="./bowser 64/74.gif"))
    vec.append (PhotoImage (file="./bowser 64/75.gif"))
    vec.append (PhotoImage (file="./bowser 64/76.gif"))
    vec.append (PhotoImage (file="./bowser 64/77.gif"))
    vec.append (PhotoImage (file="./bowser 64/78.gif"))
    vec.append (PhotoImage (file="./bowser 64/79.gif"))
    vec.append (PhotoImage (file="./bowser 64/80.gif"))
    vec.append (PhotoImage (file="./bowser 64/81.gif"))
    vec.append (PhotoImage (file="./bowser 64/82.gif"))
    vec.append (PhotoImage (file="./bowser 64/83.gif"))
    vec.append (PhotoImage (file="./bowser 64/84.gif"))
    vec.append (PhotoImage (file="./bowser 64/85.gif"))
    vec.append (PhotoImage (file="./bowser 64/86.gif"))
    vec.append (PhotoImage (file="./bowser 64/87.gif"))
    vec.append (PhotoImage (file="./bowser 64/88.gif"))
    vec.append (PhotoImage (file="./bowser 64/89.gif"))
    vec.append (PhotoImage (file="./bowser 64/90.gif"))
    vec.append (PhotoImage (file="./bowser 64/91.gif"))
    vec.append (PhotoImage (file="./bowser 64/92.gif"))
    vec.append (PhotoImage (file="./bowser 64/93.gif"))
    vec.append (PhotoImage (file="./bowser 64/94.gif"))
    vec.append (PhotoImage (file="./bowser 64/95.gif"))
    vec.append (PhotoImage (file="./bowser 64/96.gif"))
    vec.append (PhotoImage (file="./bowser 64/97.gif"))
    vec.append (PhotoImage (file="./bowser 64/98.gif"))
    vec.append (PhotoImage (file="./bowser 64/99.gif"))
    vec.append (PhotoImage (file="./bowser 64/100.gif"))
    vec.append (PhotoImage (file="./bowser 64/101.gif"))
    vec.append (PhotoImage (file="./bowser 64/102.gif"))
    vec.append (PhotoImage (file="./bowser 64/103.gif"))
    vec.append (PhotoImage (file="./bowser 64/104.gif"))
    vec.append (PhotoImage (file="./bowser 64/105.gif"))
    vec.append (PhotoImage (file="./bowser 64/106.gif"))
    vec.append (PhotoImage (file="./bowser 64/107.gif"))
    vec.append (PhotoImage (file="./bowser 64/108.gif"))
    vec.append (PhotoImage (file="./bowser 64/109.gif"))
    vec.append (PhotoImage (file="./bowser 64/110.gif"))
    vec.append (PhotoImage (file="./bowser 64/111.gif"))
    vec.append (PhotoImage (file="./bowser 64/112.gif"))
    vec.append (PhotoImage (file="./bowser 64/113.gif"))
    vec.append (PhotoImage (file="./bowser 64/114.gif"))
    vec.append (PhotoImage (file="./bowser 64/115.gif"))
    vec.append (PhotoImage (file="./bowser 64/116.gif"))
    vec.append (PhotoImage (file="./bowser 64/117.gif"))
    vec.append (PhotoImage (file="./bowser 64/118.gif"))
    vec.append (PhotoImage (file="./bowser 64/119.gif"))
    vec.append (PhotoImage (file="./bowser 64/120.gif"))
    vec.append (PhotoImage (file="./bowser 64/121.gif"))
    vec.append (PhotoImage (file="./bowser 64/122.gif"))
    vec.append (PhotoImage (file="./bowser 64/123.gif"))
    vec.append (PhotoImage (file="./bowser 64/124.gif"))
    vec.append (PhotoImage (file="./bowser 64/125.gif"))
    vec.append (PhotoImage (file="./bowser 64/126.gif"))
    pygame.mixer.music.play (1)
    for i in range(0,126):
        win.config(image=vec[i])
        raiz.update()
        sleep(.03)
    win.config(image=fondo)
    raiz.update()

##gif empate
def Empate():
    pygame.init ()
    pygame.mixer.music.load ("sonido4.2.mp3")
    vec = [(PhotoImage (file="./Empate/0.gif"))]
    vec.append (PhotoImage (file="./Empate/1.gif"))
    vec.append (PhotoImage (file="./Empate/2.gif"))
    vec.append (PhotoImage (file="./Empate/3.gif"))
    vec.append (PhotoImage (file="./Empate/4.gif"))
    vec.append (PhotoImage (file="./Empate/5.gif"))
    vec.append (PhotoImage (file="./Empate/6.gif"))
    vec.append (PhotoImage (file="./Empate/7.gif"))
    vec.append (PhotoImage (file="./Empate/8.gif"))
    vec.append (PhotoImage (file="./Empate/9.gif"))
    vec.append (PhotoImage (file="./Empate/10.gif"))
    vec.append (PhotoImage (file="./Empate/11.gif"))
    vec.append (PhotoImage (file="./Empate/12.gif"))
    vec.append (PhotoImage (file="./Empate/13.gif"))
    vec.append (PhotoImage (file="./Empate/14.gif"))
    vec.append (PhotoImage (file="./Empate/15.gif"))
    vec.append (PhotoImage (file="./Empate/16.gif"))
    vec.append (PhotoImage (file="./Empate/17.gif"))
    vec.append (PhotoImage (file="./Empate/18.gif"))
    vec.append (PhotoImage (file="./Empate/19.gif"))
    vec.append (PhotoImage (file="./Empate/20.gif"))
    vec.append (PhotoImage (file="./Empate/21.gif"))
    vec.append (PhotoImage (file="./Empate/22.gif"))
    vec.append (PhotoImage (file="./Empate/23.gif"))
    vec.append (PhotoImage (file="./Empate/24.gif"))
    vec.append (PhotoImage (file="./Empate/25.gif"))
    vec.append (PhotoImage (file="./Empate/26.gif"))
    vec.append (PhotoImage (file="./Empate/27.gif"))
    vec.append (PhotoImage (file="./Empate/28.gif"))
    vec.append (PhotoImage (file="./Empate/29.gif"))
    vec.append (PhotoImage (file="./Empate/30.gif"))
    vec.append (PhotoImage (file="./Empate/31.gif"))
    vec.append (PhotoImage (file="./Empate/32.gif"))
    vec.append (PhotoImage (file="./Empate/33.gif"))
    vec.append (PhotoImage (file="./Empate/34.gif"))
    vec.append (PhotoImage (file="./Empate/35.gif"))
    vec.append (PhotoImage (file="./Empate/36.gif"))
    vec.append (PhotoImage (file="./Empate/37.gif"))
    vec.append (PhotoImage (file="./Empate/38.gif"))
    vec.append (PhotoImage (file="./Empate/39.gif"))
    vec.append (PhotoImage (file="./Empate/40.gif"))
    vec.append (PhotoImage (file="./Empate/41.gif"))
    vec.append (PhotoImage (file="./Empate/42.gif"))
    vec.append (PhotoImage (file="./Empate/43.gif"))
    vec.append (PhotoImage (file="./Empate/44.gif"))
    vec.append (PhotoImage (file="./Empate/45.gif"))
    vec.append (PhotoImage (file="./Empate/46.gif"))
    vec.append (PhotoImage (file="./Empate/47.gif"))
    vec.append (PhotoImage (file="./Empate/48.gif"))
    vec.append (PhotoImage (file="./Empate/49.gif"))
    vec.append (PhotoImage (file="./Empate/50.gif"))
    vec.append (PhotoImage (file="./Empate/51.gif"))
    vec.append (PhotoImage (file="./Empate/52.gif"))
    vec.append (PhotoImage (file="./Empate/53.gif"))
    vec.append (PhotoImage (file="./Empate/54.gif"))
    vec.append (PhotoImage (file="./Empate/55.gif"))
    vec.append (PhotoImage (file="./Empate/56.gif"))
    vec.append (PhotoImage (file="./Empate/57.gif"))
    vec.append (PhotoImage (file="./Empate/58.gif"))
    vec.append (PhotoImage (file="./Empate/59.gif"))
    vec.append (PhotoImage (file="./Empate/60.gif"))
    vec.append (PhotoImage (file="./Empate/61.gif"))
    vec.append (PhotoImage (file="./Empate/62.gif"))
    vec.append (PhotoImage (file="./Empate/63.gif"))
    vec.append (PhotoImage (file="./Empate/64.gif"))
    vec.append (PhotoImage (file="./Empate/65.gif"))
    vec.append (PhotoImage (file="./Empate/66.gif"))
    vec.append (PhotoImage (file="./Empate/67.gif"))
    vec.append (PhotoImage (file="./Empate/68.gif"))
    vec.append (PhotoImage (file="./Empate/69.gif"))
    vec.append (PhotoImage (file="./Empate/70.gif"))
    vec.append (PhotoImage (file="./Empate/71.gif"))
    vec.append (PhotoImage (file="./Empate/72.gif"))
    vec.append (PhotoImage (file="./Empate/73.gif"))
    vec.append (PhotoImage (file="./Empate/74.gif"))
    vec.append (PhotoImage (file="./Empate/75.gif"))
    vec.append (PhotoImage (file="./Empate/76.gif"))
    vec.append (PhotoImage (file="./Empate/77.gif"))
    vec.append (PhotoImage (file="./Empate/78.gif"))
    vec.append (PhotoImage (file="./Empate/79.gif"))
    vec.append (PhotoImage (file="./Empate/80.gif"))
    vec.append (PhotoImage (file="./Empate/81.gif"))
    vec.append (PhotoImage (file="./Empate/82.gif"))
    vec.append (PhotoImage (file="./Empate/83.gif"))
    vec.append (PhotoImage (file="./Empate/84.gif"))
    vec.append (PhotoImage (file="./Empate/85.gif"))
    vec.append (PhotoImage (file="./Empate/86.gif"))
    vec.append (PhotoImage (file="./Empate/87.gif"))
    vec.append (PhotoImage (file="./Empate/88.gif"))
    vec.append (PhotoImage (file="./Empate/89.gif"))
    vec.append (PhotoImage (file="./Empate/90.gif"))
    vec.append (PhotoImage (file="./Empate/91.gif"))
    vec.append (PhotoImage (file="./Empate/92.gif"))
    vec.append (PhotoImage (file="./Empate/93.gif"))
    vec.append (PhotoImage (file="./Empate/94.gif"))
    vec.append (PhotoImage (file="./Empate/95.gif"))
    vec.append (PhotoImage (file="./Empate/96.gif"))
    vec.append (PhotoImage (file="./Empate/97.gif"))
    vec.append (PhotoImage (file="./Empate/98.gif"))
    vec.append (PhotoImage (file="./Empate/99.gif"))
    vec.append (PhotoImage (file="./Empate/100.gif"))
    vec.append (PhotoImage (file="./Empate/101.gif"))
    vec.append (PhotoImage (file="./Empate/102.gif"))
    vec.append (PhotoImage (file="./Empate/103.gif"))
    vec.append (PhotoImage (file="./Empate/104.gif"))
    vec.append (PhotoImage (file="./Empate/105.gif"))
    vec.append (PhotoImage (file="./Empate/106.gif"))
    vec.append (PhotoImage (file="./Empate/107.gif"))
    vec.append (PhotoImage (file="./Empate/108.gif"))
    vec.append (PhotoImage (file="./Empate/109.gif"))
    vec.append (PhotoImage (file="./Empate/110.gif"))
    vec.append (PhotoImage (file="./Empate/111.gif"))
    vec.append (PhotoImage (file="./Empate/112.gif"))
    vec.append (PhotoImage (file="./Empate/113.gif"))
    vec.append (PhotoImage (file="./Empate/114.gif"))
    vec.append (PhotoImage (file="./Empate/115.gif"))
    vec.append (PhotoImage (file="./Empate/116.gif"))
    vec.append (PhotoImage (file="./Empate/117.gif"))
    vec.append (PhotoImage (file="./Empate/118.gif"))
    vec.append (PhotoImage (file="./Empate/119.gif"))
    vec.append (PhotoImage (file="./Empate/120.gif"))
    vec.append (PhotoImage (file="./Empate/121.gif"))
    vec.append (PhotoImage (file="./Empate/122.gif"))
    vec.append (PhotoImage (file="./Empate/123.gif"))
    vec.append (PhotoImage (file="./Empate/124.gif"))
    vec.append (PhotoImage (file="./Empate/125.gif"))
    vec.append (PhotoImage (file="./Empate/126.gif"))
    vec.append (PhotoImage (file="./Empate/127.gif"))
    vec.append (PhotoImage (file="./Empate/128.gif"))
    vec.append (PhotoImage (file="./Empate/129.gif"))
    vec.append (PhotoImage (file="./Empate/130.gif"))
    pygame.mixer.music.play (1)

    for i in range (0,130):
        win.config (image=vec[i])
        raiz.update ()
        sleep (.02)
    win.config (image=fondo)
    raiz.update ()

##Funcion de reiniciar
def reiniciar():
   marcador.config (textvariable=jugador)
   jugador.set("MARIO")
   boton.config(state=NORMAL,image=bloque2)
   boton2.config (state=NORMAL,image=bloque2)
   boton3.config (state=NORMAL,image=bloque2)
   boton4.config (state= NORMAL,image=bloque2)
   boton5.config (state= NORMAL,image=bloque2)
   boton6.config (state= NORMAL,image=bloque2)
   boton7.config (state= NORMAL,image=bloque2)
   boton8.config (state= NORMAL,image=bloque2)
   boton9.config (state= NORMAL,image=bloque2)
   g1.set ("1")
   g2.set ("2")
   g3.set ("3")
   g4.set ("4")
   g5.set ("5")
   g6.set ("6")
   g7.set ("7")
   g8.set ("8")
   g9.set ("9")
   empate.set("9")

##Funcion de reiniciar marcador
def R_contador():
   contador.set ("0")
   contador2.set ("0")
   despliega1.config (state=NORMAL)
   despliega2.config (state=NORMAL)
   pygame.init ()
   pygame.mixer.music.load ("sonido1.mp3")
   pygame.mixer.music.play (2)

##Bloqueo de los combobox
def nombre1(event):
    despliega1.config(state=DISABLED)
def nombre2(event):
    despliega2.config(state=DISABLED)
##Desactiva audio de fondo
def muteo():
    pygame.init ()
    pygame.mixer.music.load ("sonido1.mp3")
    pygame.mixer.pause ()

##Programacion de botones
def posicion1():
    if jugador.get()=="MARIO":
        boton.config(image= Retro_Mario2)
        g1.set("MARIO")
        jugador.set("BOWSER")
        boton.config ( state = DISABLED )
    else:
        jugador.get () == "BOWSER"
        boton.config ( image = bowser)
        jugador.set ("MARIO")
        g1.set ( "BOWSER" )
        boton.config ( state = DISABLED )
    empate.set(int(empate.get())-int(fin.get()))
    valida()
def posicion2():
    if jugador.get()=="MARIO":
        boton2.config(image= Retro_Mario2)
        g2.set("MARIO")
        jugador.set("BOWSER")
        boton2.config ( state = DISABLED )
    else:
        jugador.get () == "BOWSER"
        boton2.config (image=bowser)
        jugador.set ("MARIO")
        g2.set ("BOWSER")
        boton2.config (state=DISABLED)
    empate.set (int (empate.get ()) - int (fin.get ()))
    valida ()
def posicion3():
    if jugador.get () == "MARIO":
        boton3.config ( image = Retro_Mario2 )
        g3.set ( "MARIO" )
        jugador.set ( "BOWSER" )
        boton3.config ( state = DISABLED )
    else:
        jugador.get () == "BOWSER"
        boton3.config (image=bowser)
        jugador.set ("MARIO")
        g3.set ("BOWSER")
        boton3.config (state=DISABLED)
    empate.set (int (empate.get ()) - int (fin.get ()))
    valida()
def posicion4():
    if jugador.get () == "MARIO":
        boton4.config ( image = Retro_Mario2 )
        g4.set ( "MARIO" )
        jugador.set ( "BOWSER" )
        boton4.config ( state = DISABLED )
    else:
        jugador.get () == "BOWSER"
        boton4.config (image=bowser)
        jugador.set ("MARIO")
        g4.set ("BOWSER")
        boton4.config (state=DISABLED)
    empate.set (int (empate.get ()) - int (fin.get ()))
    valida ()
def posicion5():
    if jugador.get () == "MARIO":
        boton5.config ( image = Retro_Mario2 )
        g5.set ( "MARIO" )
        jugador.set ( "BOWSER" )
        boton5.config ( state = DISABLED )
    else:
        jugador.get () == "BOWSER"
        boton5.config (image=bowser)
        jugador.set ("MARIO")
        g5.set ("BOWSER")
        boton5.config (state=DISABLED)
    empate.set (int (empate.get ()) - int (fin.get ()))
    valida ()
def posicion6():
    if jugador.get () == "MARIO":
        boton6.config ( image = Retro_Mario2 )
        g6.set ( "MARIO" )
        jugador.set ( "BOWSER" )
        boton6.config ( state = DISABLED )
    else:
        jugador.get () == "BOWSER"
        boton6.config (image=bowser)
        jugador.set ("MARIO")
        g6.set ("BOWSER")
        boton6.config (state=DISABLED)
    empate.set (int (empate.get ()) - int (fin.get ()))
    valida ()
def posicion7():
    if jugador.get () == "MARIO":
        boton7.config ( image = Retro_Mario2 )
        g7.set ( "MARIO" )
        jugador.set ( "BOWSER" )
        boton7.config ( state = DISABLED )
    else:
        jugador.get () == "BOWSER"
        boton7.config (image=bowser)
        jugador.set ("MARIO")
        g7.set ("BOWSER")
        boton7.config (state=DISABLED)
    empate.set (int (empate.get ()) - int (fin.get ()))
    valida ()
def posicion8():
    if jugador.get () == "MARIO":
        boton8.config ( image = Retro_Mario2 )
        g8.set ( "MARIO" )
        jugador.set ( "BOWSER" )
        boton8.config ( state = DISABLED )
    else:
        jugador.get () == "BOWSER"
        boton8.config (image=bowser)
        jugador.set ("MARIO")
        g8.set ("BOWSER")
        boton8.config (state=DISABLED)
    empate.set (int (empate.get ()) - int (fin.get ()))
    valida ()
def posicion9():
    if jugador.get () == "MARIO":
        boton9.config ( image = Retro_Mario2 )
        g9.set ( "MARIO" )
        jugador.set ( "BOWSER" )
        boton9.config ( state = DISABLED )
    else:
        jugador.get() == "BOWSER"
        boton9.config (image=bowser)
        jugador.set ("MARIO")
        g9.set ("BOWSER")
        boton9.config (state=DISABLED)
    empate.set (int (empate.get ()) - int (fin.get ()))
    valida ()
    boton9.config (state=DISABLED)

##---------------------------------------------Procedimiento principal--------------------------------------------------
##En este procceso se valida el ganador
def valida():
    if g1.get()==g2.get() and g1.get()==g3.get():
        if g1.get()=="MARIO":
            celebra_mario()
            messagebox.showinfo(message="Gano "+despliega1.get())
            contador.set(int(contador.get())+int(suma.get()))
        else:
            celebra_bowser()
            messagebox.showinfo ( message = "Gano "+despliega2.get() )
            contador2.set (int (contador2.get ()) + int (suma2.get ()))
        reiniciar()
    elif g4.get()==g5.get() and g4.get()==g6.get():
        if g4.get()=="MARIO":
            celebra_mario()
            messagebox.showinfo ( message = "Gano "+despliega1.get() )
            contador.set (int (contador.get ()) + int (suma.get ()))
        else:
            celebra_bowser()
            messagebox.showinfo ( message = "Gano "+despliega2.get() )
            contador2.set (int (contador2.get ()) + int (suma2.get ()))
        reiniciar()
    elif g7.get () == g8.get () and g7.get () == g9.get ():
        if g7.get () == "MARIO":
            celebra_mario()
            messagebox.showinfo ( message = "Gano "+despliega1.get() )
            contador.set (int (contador.get ()) + int (suma.get ()))
        else:
            celebra_bowser()
            messagebox.showinfo ( message = "Gano "+despliega2.get() )
            contador2.set (int (contador2.get ()) + int (suma2.get ()))
        reiniciar()
    elif g1.get () == g5.get () and g1.get () == g9.get ():
        if g1.get () == "MARIO":
            celebra_mario()
            messagebox.showinfo ( message = "Gano "+despliega1.get() )
            contador.set (int (contador.get ()) + int (suma.get ()))
        else:
            celebra_bowser()
            messagebox.showinfo ( message = "Gano "+despliega2.get())
            contador2.set (int (contador2.get ()) + int (suma2.get ()))
    elif g3.get () == g5.get () and g3.get () == g7.get ():
        if g3.get () == "MARIO":
            celebra_mario()
            messagebox.showinfo ( message = "Gano "+despliega1.get() )
            contador.set (int (contador.get ()) + int (suma.get ()))
        else:
            celebra_bowser()
            messagebox.showinfo ( message = "Gano "+despliega2.get() )
            contador2.set (int (contador2.get ()) + int (suma2.get ()))
        reiniciar()
    elif g1.get () == g4.get () and g1.get () == g7.get ():
        if g1.get () == "MARIO":
            celebra_mario()
            messagebox.showinfo (message="Gano "+despliega1.get())
            contador.set (int (contador.get ()) + int (suma.get ()))
        else:
            celebra_bowser()
            messagebox.showinfo (message="Gano "+despliega2.get())
            contador2.set (int (contador2.get ()) + int (suma2.get ()))
        reiniciar()
    elif g3.get () == g6.get () and g3.get () == g9.get ():
        if g3.get () == "MARIO":
            celebra_mario()
            messagebox.showinfo (message="Gano"+despliega2.get())
            contador.set (int (contador.get ()) + int (suma.get ()))
        else:
            celebra_bowser()
            messagebox.showinfo (message="Gano "+despliega2.get())
            contador2.set (int (contador2.get ()) + int (suma2.get ()))
        reiniciar()
    elif  g2.get () == g5.get () and g2.get () == g8.get ():
        if g2.get () == "MARIO":
            celebra_mario()
            messagebox.showinfo (message="Gano "+despliega1.get())
            contador.set (int (contador.get ()) + int (suma.get ()))
        else:
            celebra_bowser()
            messagebox.showinfo (message="Gano "+despliega2.get())
            contador2.set (int (contador2.get ()) + int (suma2.get ()))
        reiniciar()
    elif empate.get()=="0":
         Empate()
         messagebox.showinfo(message="Empate")

##Etiquetas con la informacion para el usario
texto=Label(raiz,bg="snow3",text="JUEGO DEL GATO",font="Hevetica 18 bold",)
texto.place(x=100,y=40)

texto2=Label(raiz,bg="snow3",text="TURNO",font="Hevetica 18 bold")
texto2.place(x=450,y=60)

marcador=Label(raiz,bg="snow3",textvariable=jugador)
marcador.place(x=550,y=65)

campo=Entry(raiz,bg="snow",font="Hevetica 18 bold",width=2,state=DISABLED,textvariable=contador)
campo.place(x=495,y=100)

campo2=Entry(raiz,bg="snow",font="Hevetica 18 bold",width=2,state=DISABLED,textvariable=contador2)
campo2.place(x=495,y=150)

##Separaciones para el tablero
borde=Label(raiz,bg="gray1",width=40,height=18)
borde.place(x=65,y=95)
borde2=Label(raiz,bg="gold",width=39,height=17)
borde2.place(x=68,y=98)

##Creacion y asignacion de botones
boton=Button(raiz,text=".",command=posicion1,image=bloque2,textvariable=g1)
boton.place(height=72,width=72,x=75,y=100)
boton2=Button(raiz,text=".",command=posicion2,image=bloque2,textvariable=g2)
boton2.place(height=72,width=72,x=172,y=100)
boton3=Button( raiz, text=".", command=posicion3,image=bloque2,textvariable=g3 )
boton3.place(height=72,width=72,x=269,y=100)
boton4=Button(raiz,text=".",command=posicion4,image=bloque2,textvariable=g4)
boton4.place(height=72,width=72,x=75,y=190)
boton5=Button(raiz,text=".",command=posicion5,image=bloque2,textvariable=g5 )
boton5.place(height=72,width=72,x=172,y=190)
boton6=Button(raiz,text=".",command=posicion6,image=bloque2,textvariable=g6)
boton6.place(height=72,width=72,x=269,y=190)
boton7=Button(raiz,text=".",command=posicion7,image=bloque2,textvariable=g7)
boton7.place(height=72,width=72,x=75,y=280)
boton8=Button(raiz,text=".",command=posicion8,image=bloque2,textvariable=g8)
boton8.place(height=72,width=72,x=172,y=280)
boton9=Button(raiz,text=".",command=posicion9,image=bloque2,textvariable=g9)
boton9.place(height=72,width=72,x=269,y=280)
reset=Button(raiz,text="Reiniciar",width=7,command=reiniciar)
reset.place(x=355,y=280)
reset2=Button(raiz,text="Nueva partida",command=R_contador)
reset2.place(x=430,y=280)
Config=Button(raiz,text="Configuracion",command=abre)
Config.place(x=530,y=280)
up=Button(raiz,text="Actualizar",command=update)
up.place(x=630,y=280)
m=Button(raiz,text="Silencio",command=muteo)
m.place(x=600,y=20)
Base()
despliega1.bind ("<<ComboboxSelected>>", nombre1)
despliega2.bind ("<<ComboboxSelected>>", nombre2)
##En donde reside el gif
win=Label(raiz,image=etiqueta)
win.place(x=1,y=1)

raiz.mainloop()
